# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: setting git data
        run: |
          git config user.name "Clerk"
          git config user.email "<>"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          # Getting the updated code.
          git checkout main;
          git pull;
          
          # Getting the commit description.
          COMMIT_HASH=$(git rev-parse --short HEAD);
          COMMIT_TITLE=$(git log -n 1 --pretty=format:'%s');
          COMMIT_DESCRIPTION=$(git log -n 1 --pretty=format:'%b');
          
          # Changing to the branch of build logs.
          git checkout build-logs;
          
          # Adding the commit on BUILDS file.
          echo "
          ## $COMMIT_TITLE ($COMMIT_HASH).
          $COMMIT_DESCRIPTION
          " >> BUILDS.MD;
          
          # Saving the modification.
          git add BUILDS.MD;
          git commit -m ":books:DOCS: Saves message of commit $COMMIT_HASH on BUILDS file";
          git push;
